print("what is your first name")
x=input()
print("what is your middle name (optional)")
c=input()
print("what is your last name")
y=input()
print("what year were you born")
z=input()
print("what month were you born")
a=input()
print("what day were you born")
b=input()
print("your ID is...")
print(x+c+y+","+z+","+a+","+b)